---

- name: "Destroy Lab Network Machines"
  hosts: all
  remote_user: root
  gather_facts: false

  vars:
    libvirt_host: "qemu+ssh://{{ ansible_ssh_host }}/system?socket=/var/run/libvirt/libvirt-sock"

  tasks:
    - name: "Register all VMs"
      virt:
        command: list_vms
        uri: "{{ libvirt_host }}"
      register: vms

    - name: "Stop all VMs"
      virt:
        name: "{{ item }}"
        state: destroyed
        uri:  "{{ libvirt_host }}"
      when: item == "loadbalancer" or item == "firewall"
      with_items: "{{ vms.list_vms }}"

    - name: "Remove all VMs"
      virt:
        name: "{{ item }}"
        command: undefine
        uri: "{{ libvirt_host }}"
      when: item == "loadbalancer" or item == "firewall"
      with_items: "{{ vms.list_vms }}"

    - name: "Remove all storage devices"
      shell: "for a in `virsh vol-list --pool storage|awk '/loadbalancer|firewall/ { print $1 }'`; \
      do virsh vol-delete $a storage; done;"
