---

- name: "Destroy Network State File"
  hosts: all
  remote_user: root
  gather_facts: false

  tasks:
    - name: "Delete lab config state file"
      command: rm -f .netconfig
      args:
        chdir: /root
