---

- name: "Prepare the Environment for Rolling Upgrade OSA"
  hosts: all
  remote_user: root
  serial: 1
  vars:
    osa_path: "{{ main_path | default('/opt/openstack-ansible') }}"
  
  tasks:
    - name: Clone openstack-ansible to a specific release
      git: 
        repo: http://github.com/openstack/openstack-ansible
        dest: "{{ osa_path }}"
        clone: yes
        accept_hostkey: yes
        recursive: yes
        version: "{{ openstack_release }}"
      tags:
        - config

    - name: Run set-pre-upgrade script to modify run-upgrade.sh
      script: scripts/77-set-pre-upgrade "{{ osa_path }}/scripts"
      tags:
        - config

    - name: Run modified run-upgrade.sh -- only pre-req plays
      shell: export TERM=xterm; echo 'YES' | I_REALLY_KNOW_WHAT_I_AM_DOING=true ./run-upgrade.sh
      args:
        chdir: "{{ osa_path }}/scripts/"
      tags:
        - pre-upgrade
